name: Build & Release

on:
  push:
    tags:
      - 'v*'  # 只有打 tag 时才触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.7.2'  # 设置你的.NET版本

      - name: Build
        run: dotnet build -c Release

      - name: Zip output
        run: Compress-Archive -Path .\bin\Release\* -DestinationPath .\release.zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
